### ISSUE TITLE
What is the equivalent of com.sun.activation:jakarta.activation in the angus world?

### ISSUE THREAD

**Issue by space88man** [eclipse-ee4j/angus-activation#25]
**Describe the bug**
I am testing the angus artifacts but without Jakarta Activation API classes inside the jar like com.sun.activation:jakarta.activation-2.0.1.jar; what is the correct way to fulfil jakarta.activation-api ?

**To Reproduce**
1. Replace  com.sun.activation:jakarta.activation with angus-actiivation alone (no API classes - app wont' start)
2. Replace with angus-activation + jakarta.activation-api:

Note: this is a slightly weird legacy app that is Java SE but uses the Spring AnnotationConfigApplicationContext  to instantiate some Beans manually

```
Caused by: java.lang.IllegalAccessError: failed to access class com.sun.activation.registries.LogSupport from class jakarta.activation.MailcapCommandMap (com.sun.activation.registries.LogSupport and jakarta.activation.MailcapCommandMap are in unnamed module of loader 'app')
```
**Expected behavior**
Replace jakarta.activation with angus-based artifacts

**Screenshots**
n/a

**Desktop (please complete the following information):**
Java 17 on Fedora 37 Linux /x86_64

**Additional context**

**Comment by lukasj** [comment]
jakarta.activation-api-2.1.0.jar (compile) + angus-activation-1.0.0.jar (runtime) Note: one need to make sure there is no com.sun.activation:jakarta.activation on the cp
