### ISSUE TITLE
Module org.eclipse.angus.activation does not read a module that exports jakarta.activation.spi

### ISSUE THREAD

**Issue by grigala** [eclipse-ee4j/angus-activation#43]
I'm working on a project that does not directly depend on Eclipse Angus dependency. 

I'm using the `org.glassfish.jaxb:jaxb-core:4.0.2` dependency which transitively pulls `angus` into the classpath. 

As a result test compilcation throws module resolution exceptions:

> java.lang.module.ResolutionException: Module org.eclipse.angus.activation does not read a module that exports jakarta.activation.spi

Is this a bug or can I do something to resolve the issue?

**Comment by grigala** [comment]
I have excluded it via Gradle and the error seems to be gone.

**Comment by lukasj** [comment]
jaxb 4+ requires activation-api 2.1+. It is likely that some other dependency brings in older version of the API
