### ISSUE TITLE
TCK for activation doesn't pass anymore on GF

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/angus-activation#6]
Every test now fails with something like:

```
[javatest.batch] command: com.sun.javatest.lib.ExecStdTestOtherJVMCmd CLASSPATH=/home/jenkins/agent/workspace/jaf-tck_master/activation-tck/tests/../classes:/home/jenkins/agent/workspace/jaf-tck_master/JTwork/activation-tck/classes:/home/jenkins/agent/workspace/jaf-tck_master/activation-tck/javatest.jar:/home/jenkins/agent/workspace/jaf-tck_master/activation-tck/sigtest.jar:/home/jenkins/agent/workspace/jaf-tck_master/jakarta.activation.jar:/home/jenkins/agent/workspace/jaf-tck_master/activation-tck/classes HOME=/ /opt/jdk-11.0.10/bin/java -verify javasoft.sqe.tests.api.jakarta.activation.ActivationDataFlavor.ActivationDataFlavor_Test
[javatest.batch] java.lang.NoClassDefFoundError: jakarta/activation/ActivationDataFlavor
[javatest.batch] 	at javasoft.sqe.tests.api.jakarta.activation.ActivationDataFlavor.ActivationDataFlavor_Test.callADF_1(ActivationDataFlavor_Test.java:61)
[javatest.batch] 	at javasoft.sqe.tests.api.jakarta.activation.ActivationDataFlavor.ActivationDataFlavor_Test.testForActivationDF1(ActivationDataFlavor_Test.java:44)
[javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javatest.batch] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javatest.batch] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[javatest.batch] 	at com.sun.javatest.lib.TestCases.invokeTestCases(TestCases.java:195)
[javatest.batch] 	at com.sun.javatest.lib.MultiTest.run(MultiTest.java:134)
[javatest.batch] 	at javasoft.sqe.tests.api.jakarta.activation.ActivationDataFlavor.ActivationDataFlavor_Test.main(ActivationDataFlavor_Test.java:37)
[javatest.batch] Caused by: java.lang.ClassNotFoundException: jakarta.activation.ActivationDataFlavor
[javatest.batch] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
[javatest.batch] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[javatest.batch] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[javatest.batch] 	... 9 more
```

See: https://ci.eclipse.org/jakartaee-tck/job/jaf-tck/job/master/47/consoleFull

@lukasj any idea what could be causing this?

**Comment by lukasj** [comment]
wrong TCK? why are you running 2.1-dev TCK on 2.0 impl?

**Comment by lukasj** [comment]
also since https://github.com/eclipse-ee4j/glassfish/pull/23695 has not been merged, this project is the wrong one to blame

**Comment by arjantijms** [comment]
> wrong TCK? why are you running 2.1-dev TCK on 2.0 impl?

I'm running the EE9.1 standalone TCK, which somehow triggers that. I'm not sure where/why/how the choice is made between 9.1 and the 10 that's half in development.

> also since eclipse-ee4j/glassfish#23695 has not been merged, this project is the wrong one to blame

Does that matter then? Since as far as I can tell the job doesn't actually use GF. It gets the jars from https, and does nothing with GF.

**Comment by arjantijms** [comment]
Just to be clear, I'm running this job:

https://ci.eclipse.org/jakartaee-tck/view/EPL-EFTL-CERTIFICATION-JOBS/job/eftl-standalonetck-certification/

That somehow invokes this job:

https://ci.eclipse.org/jakartaee-tck/job/jaf-tck/

But how can we do certifications for 9.1 still?

1. 9.1 is gone? So 9.1 certifications must stop?
2. It didn't even test the server really, but gets it jars from https, so how did we ever test the actual server bits?

I see it downloading this in the job:

```
ACTIVATION_BUNDLE_URL=https://jakarta.oss.sonatype.org/content/repositories/staging/com/sun/activation/jakarta.activation/2.0.0/jakarta.activation-2.0.0.jar

ANGUS_BUNDLE_URL=https://jakarta.oss.sonatype.org/content/repositories/staging/org/eclipse/angus/angus-activation/1.0.0-SNAPSHOT/angus-activation-1.0.0-20210811.141336-3.jar
```

There's never any reference to GF. What am I missing there?

**Comment by lukasj** [comment]
This project is never going to be compatible with JAF 2.0. First version of this project is going to be 1.0.0 and will implement JAF 2.1, so it is very unlikely this can ever pass EE 9.1 TCK, so if a job running EE 9.1 TCK tests for whatever reason angus, then the job is wrong.

What I think that job should do is:
* grab appropriate version of the TCK and unzip
* grab glassfish and unzip 
* update paths in TCK's ts.jte to point to the right jars from the unzipped server (what if GF uses ie awsomeGFact.jar instead of current jakarta.activation.jar?)
* run the TCK

...but how is that related to this particular project? Doesn't this conversation belong to either jaf-tck, gf or platform-tck repo/lists instead?

**Comment by arjantijms** [comment]
> What I think that job should do is:
> [logical list of steps]

That seems a bit more logical, and I thought that was what was happening, but it's not the case at all.

> ...but how is that related to this particular project? Doesn't this conversation belong to either jaf-tck, gf or platform-tck repo/lists instead?

I wasn't really sure where to ask upon seeing it failing. Initially it looked like Angus failing, but upon a closer look it appeared to be the TCK itself. I moved the discussion to jaf-tck.

**Comment by lukasj** [comment]
> I wasn't really sure where to ask upon seeing it failing. Initially it looked like Angus failing, but upon a closer look it appeared to be the TCK itself. I moved the discussion to jaf-tck.

no problem at all
